# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('slug', models.SlugField(help_text='A label identifying the blog post URL', max_length=63,
                                          unique_for_month='publication_date')),
                ('text', models.TextField()),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('products', models.ManyToManyField(to='product.Product')),
                ('tags', models.ManyToManyField(to='product.Tag')),
            ],
            options={
                'ordering': ['-publication_date', 'title'],
                'get_latest_by': 'publication_date',
            },
        ),
    ]
